[package]
name = "libsignal-sys"
version = "0.1.0"
authors = ["Fabrice Desré <fabrice@desre.org>"]
edition = "2018"
license = "KaiOS"
publish = false

[dependencies]
aes = "0.7"
arrayref = "0.3"
block-modes = "0.8"
ctr = "0.7"
hmac = "0.10"
log = "0.4"
prost = "0.7"
prost-derive = "0.7"
ring = "0.16"
sha2 = "0.9"

[build-dependencies]
cc = "1.0"
prost-build = "0.7"
