[general]
host = "127.0.0.1"
port = 80
message_max_time = 10 # In ms.
verbose_log = false
log_path = "/data/local"
remote_services_config = "/data/local/service/api-daemon/remote_services.toml"
remote_services_path = "/system/api-daemon/remote"
socket_path = "/dev/socket/api-daemon"

[http]
root_path = "/system/api-daemon/http_root"

[vhost]
root_path = "/data/local/webapps/vroot"
csp = "default-src * data: blob:; script-src 'self' http://127.0.0.1 http://shared.localhost; object-src 'none'; style-src 'self' 'unsafe-inline' http://shared.localhost"

[apps_service]
root_path = "/system/b2g/webapps"
data_path = "/data/local/webapps"
uds_path = "/data/local/tmp/apps-uds.sock"
cert_type = "production"
updater_socket = "/dev/socket/updater_socket"
user_agent = "Mozilla/5.0 (Mobile; rv:90.0) Gecko/90.0 Firefox/90.0 B2GOS/3.2"
allow_remove_preloaded = true
