# Configuration file usable for desktop builds.

[general]
host = "0.0.0.0"
port = 8081
message_max_time = 10 # In ms.
verbose_log = true
log_path = "/tmp"
remote_services_config = "./remote/config.toml"
remote_services_path = "./remote"
socket_path = "/tmp/api-daemon-socket"

[http]
root_path = "../prebuilts/http_root"

[vhost]
root_path = "../prebuilts/http_root/webapps/vroot"
csp = "default-src * data: blob:; script-src 'self' http://127.0.0.1 http://shared.localhost; object-src 'none'; style-src 'self' 'unsafe-inline' http://shared.localhost"

[apps_service]
root_path = "../services/apps/test-fixtures/webapps"
data_path = "../prebuilts/http_root/webapps"
uds_path = "/tmp/apps_service_uds.sock"
cert_type = "test"
updater_socket = "/tmp/updater_socket"
user_agent = "Mozilla/5.0 (Mobile; rv:90.0) Gecko/90.0 Firefox/90.0 B2GOS/3.2"
