[general]
host = "0.0.0.0"
port = 8081
message_max_time = 10
verbose_log = false
log_path = "/tmp"
remote_services_config = "remote_config.toml"
remote_services_path = "./remote/"
socket_path = "/dev/socket/api-daemon"

[http]
root_path = "/tmp"

[vhost]
root_path = "/tmp/apps"
csp = "default-src * data: blob:; script-src 'self' http://127.0.0.1 http://shared.localhost; object-src 'none'; style-src 'self' 'unsafe-inline' http://shared.localhost"

[apps_service]
root_path = "/tmp/test-fixtures/webapps"
data_path = "/tmp/apps"
uds_path = "/tmp/uds_tmp.sock"
cert_type = "test"
updater_socket = "/tmp/updater_socket"
user_agent = "Custom user-agent"
